name: Build and Test Package

on:
  push:
    branches:
      - main
      - feature/*
      - enh/1/testing-python-code
      - enh/3/refactor-code
      - enh/5/unit-test
      - enh/7/modular
      - enh/9/log
      - enh/11/docs
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8

      - name: Install Tree CLI
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Display directory structure before installation
        run: |
          echo "Directory structure before installation:"
          tree -L 3 .

      - name: Install package in dev mode
        run: |
          conda install pip
          pip install -e .
          pip install pytest isort flake8 black


      - name: Run isort check
        run: isort . --check --profile black

      - name: Run Flake8 check
        run: flake8 .

      - name: Run Black check
        run: black . --check

      - name: Run unit tests
        run: python -m pytest tests/ -v

  build-docs:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8

      - name: Install Tree CLI
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Display directory structure before building docs
        run: |
          echo "Directory structure before building docs:"
          tree -L 3 .

      - name: Install package and documentation dependencies
        run: |
          conda install pip
          pip install -e .
          pip install sphinx sphinx-autodoc-typehints

      - name: Build documentation
        run: |
          cd docs
          make html

      - name: Display directory structure after building docs
        run: |
          echo "Directory structure after building docs:"
          tree -L 3 .

      - name: Archive documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation-html
          path: docs/build/html/

  build:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8

      - name: Install Tree CLI
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Install build dependencies
        run: |
          conda install pip
          pip install build wheel pytest

      - name: Build package
        run: python -m build

      - name: Display directory structure after build
        run: |
          echo "Directory structure after build:"
          tree -L 3 .

      - name: Install package from wheel
        run: pip install dist/*.whl

      - name: Run installation tests
        run: python -m pytest tests/test_dependencies_install.py -v

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist/

      - name: Install package
        run: pip install dist/*.whl

      - name: Create data directory
        run: mkdir -p data models results logs

      - name: Run ingest_data.py help
        run: python -m housepred.ingest_data --help

      - name: Run ingest_data.py
        run: python -m housepred.ingest_data --output-path data --log-path logs/ingest_data.log --log-level INFO

      - name: Run train.py help
        run: python -m housepred.train --help

      - name: Run train.py
        run: python -m housepred.train --input-path data/housing.csv --output-path models/housepred.pkl --model-type linear --log-path logs/train.log --log-level INFO

      - name: Run score.py help
        run: python -m housepred.score --help

      - name: Run score.py
        run: python -m housepred.score --model-path models/housepred.pkl --data-path data/housing.csv --output-path results/predictions.txt --log-path logs/score.log --log-level INFO